import 'package:flutter/material.dart';
import 'package:unping_ui/unping_ui.dart';

/// Predefined Dropdown configurations matching common design patterns
class Dropdowns {
  static BaseDropdown select(
      {label,
      onDropdownStateChanged,
      size,
      state,
      errorColor,
      errorMessage,
      isMultiSelect = false,
      isSearchable = true,
      required selectedValue,
      required onSelectedValueChanged,
      required options,
      enableKeyboardNavigation = false,
      sortMenuItems = false,
      textStyle,
      padding,
      dropdownColor,
      containerBackgroundColor,
      borderRadiusColor,
      withBorder}) {
    return BaseDropdown(
      label: label,
      state: state ?? DropdownState.normal,
      dropdownType: DropdownType.single,
      errorColor: errorColor ?? UiColors.error,
      errorMessage: errorMessage ?? 'Error',
      options: options,
      onSelectedValueChanged: onSelectedValueChanged,
      selectedValue: selectedValue,
      onDropdownStateChanged: onDropdownStateChanged,
      containerBackgroundColor: containerBackgroundColor ?? UiColors.neutral700,
      dropdownColor: dropdownColor ?? UiColors.neutral700,
      enableKeyboardNavigation: enableKeyboardNavigation,
      size: size ?? DropdownSize.md,
      borderRadiusColor: borderRadiusColor ?? UiColors.neutral300,
      withBorder: withBorder ?? true,
    );
  }

  static BaseDropdown multiSelect(
      {label,
      onDropdownStateChanged,
      size,
      state,
      errorColor,
      errorMessage,
      isMultiSelect = true,
      isSearchable = true,
      required selectedValues,
      required onSelectedValueChanged,
      required options,
      enableKeyboardNavigation = false,
      sortMenuItems = false,
      textStyle,
      padding,
      dropdownColor,
      containerBackgroundColor,
      borderRadiusColor,
      selectAllText,
      clearAllText,
      withBorder}) {
    return BaseDropdown(
      label: label,
      state: state ?? DropdownState.normal,
      dropdownType: DropdownType.multi,
      errorColor: errorColor ?? UiColors.error,
      errorMessage: errorMessage ?? 'Error',
      onSelectedValueChanged: onSelectedValueChanged!,
      selectedValues: selectedValues,
      onDropdownStateChanged: onDropdownStateChanged,
      containerBackgroundColor: containerBackgroundColor ?? UiColors.neutral700,
      dropdownColor: dropdownColor ?? UiColors.neutral700,
      enableKeyboardNavigation: enableKeyboardNavigation,
      textStyle: textStyle,
      isSearchable: isSearchable,
      isMultiSelect: isMultiSelect,
      padding: padding,
      options: options,
      size: size ?? DropdownSize.md,
      selectAllText: selectAllText ?? "Select All",
      clearAllText: clearAllText ?? "Clear All",
      borderRadiusColor: borderRadiusColor ?? UiColors.neutral300,
      withBorder: withBorder ?? true,
    );
  }

  static BaseDropdown combobox({
    label,
    onDropdownStateChanged,
    size,
    state,
    isMultiSelect = true,
    isSearchable = true,
    required onSelectedValueChanged,
    required options,
    enableKeyboardNavigation = false,
    sortMenuItems = false,
    textStyle, //assign later
    padding,
    dropdownColor,
    containerBackgroundColor,
    borderRadiusColor,
    errorMessage,
    withBorder,
  }) {
    return BaseDropdown(
      label: label,
      dropdownType: DropdownType.comboBox,
      state: state ?? DropdownState.normal,
      onSelectedValueChanged: onSelectedValueChanged!,
      onDropdownStateChanged: onDropdownStateChanged,
      containerBackgroundColor: containerBackgroundColor ?? UiColors.neutral700,
      dropdownColor: dropdownColor ?? UiColors.neutral700,
      enableKeyboardNavigation: enableKeyboardNavigation,
      textStyle: textStyle,
      isSearchable: isSearchable,
      isMultiSelect: isMultiSelect,
      padding: padding,
      options: options,
      size: size ?? DropdownSize.md,
      borderRadiusColor: borderRadiusColor ?? UiColors.neutral300,
      errorMessage: errorMessage ?? "Error Message",
      withBorder: withBorder ?? true,
    );
  }

  static BaseDropdown menu({
    label,
    dropdownType,
    state,
    onDropdownStateChanged,
    containerBackgroundColor,
    dropdownColor,
    enableKeyboardNavigation,
    textStyle,
    leadingDropdownIcon,
    trailingDropdownIcon,
    actionMenuDivider,
    actionMenuGroups,
    padding,
    options,
    size,
    borderRadiusColor,
    withBorder,
    errorMessage,
  }) {
    return BaseDropdown(
      label: label,
      dropdownType: DropdownType.action,
      state: state ?? DropdownState.normal,
      onDropdownStateChanged: onDropdownStateChanged,
      containerBackgroundColor: containerBackgroundColor ?? UiColors.neutral700,
      dropdownColor: dropdownColor ?? UiColors.neutral700,
      enableKeyboardNavigation: enableKeyboardNavigation ?? true,
      textStyle: textStyle ?? UiTextStyles.displayMd,
      leadingDropdownIcon: leadingDropdownIcon ?? const SizedBox(),
      trailingDropdownIcon: trailingDropdownIcon ?? const SizedBox(),
      actionMenuDivider: actionMenuDivider ?? true,
      actionMenuGroups: actionMenuGroups ?? [],
      padding: padding,
      options: options ?? [],
      size: size ?? DropdownSize.md,
      borderRadiusColor: borderRadiusColor ?? UiColors.neutral300,
      withBorder: withBorder ?? true,
      errorMessage: errorMessage ?? 'Error',
    );
  }
}
