name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
  workflow_dispatch:

jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: "**/*.md"
      modified_files_only: false

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable

  widgetbook-build:
    uses: ./.github/workflows/build-widgetbook.yaml

  # Discover available components
  discover-components:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.get-components.outputs.components }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get component directories
        id: get-components
        run: |
          components=$(ls -1 lib/src/components/ | jq -R -s -c 'split("\n")[:-1]')
          echo "components=$components" >> $GITHUB_OUTPUT

  # Ensure components are compatible with fpx
  fpx-compatibility:
    needs: discover-components
    strategy:
      matrix:
        component: ${{ fromJson(needs.discover-components.outputs.components) }}
    uses: jdde/fpx/.github/workflows/reusable-fpx-compatibility.yml@83aa5b937853a9a7eabc3e5491f3a17168b17fc6
    with:
      component_name: ${{ matrix.component }}
