name: Publish to Widgetbook

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  widgetbook-cloud-hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Install Appwrite CLI
        run: npm install -g appwrite-cli

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable

      - name: Install dependencies
        run: |
            flutter pub get

      - name: Build Widgetbook
        working-directory: widgetbook
        run: |
            flutter pub get
            dart run build_runner build -d
            flutter build web -t lib/main.dart
      
      - name: Copy files from build directory to appwrite webserver
        run: cp -r ./widgetbook/build/web/* appwrite/sites/unping-ui.com/

      - name: Authenticate with Appwrite
        run: cd ./appwrite && appwrite client --endpoint https://cloud.appwrite.io/v1 --project-id "${{ secrets.APPWRITE_PROJECT_ID }}" --key "${{ secrets.APPWRITE_API_KEY_GITHUB_ACTION_DEPLOYMENT_PROD }}"

      - name: Push all sites to appwrite
        run: cd ./appwrite && appwrite push sites --all --force
